### ISSUE TITLE
compiler-time optimization tracker

### ISSUE THREAD

**Issue by darkhaven3** [darkhaven3/projectFrost#3]
@TheMrIron2 use this issue thread to track the different faggy shit you do to the makefile and document your findings here when possible

**Comment by TheMrIron2** [comment]
Okay. Based on code as of commit "new QuakeC source changes are broken" (commit 31)

Optimization level flags and relative performance in `dm_killhouse` (333MHz, texture filter ON):

- O1: 10FPS (Additional note: 2.3MB EBOOT.PBP)

(Note: O1 is usually used as a debug flag for minimum possible optimizations so this is a baseline)

- O2: 10FPS (Additional note: 2.3MB EBOOT.PBP)

(Note: O2 is the default flag when compiling)

- O3: 10FPS (Additional note: 2.3MB EBOOT.PBP)

(Note: O3 is ProQuake's standard makefile flag)

- Ofast: 10FPS (Additional note: 2.3MB EBOOT.PBP)

Conclusion: Either something is going wrong, or ProQuake gains no benefit from additional compiler optimization. May double check tomorrow to see if this is still the case; PQ's repository shows signs of already having been compiled in, so this could be skewing results a bit since parts were already compiled? atm I don't have enough time to diagnose it properly, so for now that's the result.

**Comment by TheMrIron2** [comment]
Please add the "faggy" tag to this issue, thank you

**Comment by darkhaven3** [comment]
This is in line with what I expected. The data-driven nature of the engine means it is not as subject to compiler-time optimization as it would be hand-optimizing the inner render loop, for example

**Comment by TheMrIron2** [comment]
Won't close this issue just yet. This new setup is building 1.8MB EBOOTs, which is in line with what IPQ Rev4 should _actually_ be. Still want to compare performance with my newer toolchain.

I also suspect I wasn't `make clean`ing like a dumbass when testing like that, so...
